2023-01-25 08:05:12,455 - ERROR - service.py:98 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'rds.meunagumo.com.br' (timed out)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-02-02 17:15:56,333 - ERROR - service.py:47 - Erro ao gerar jogadas, cliente: 44185567880, erro: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.OperationalError) (1054, "Unknown column 'user_inclusao' in 'field list'")
[SQL: INSERT INTO bake_compras (loja, coo, checkout, valor, id_usuario, gera_jogada, user_inclusao) VALUES (%(loja)s, %(coo)s, %(checkout)s, %(valor)s, %(id_usuario)s, %(gera_jogada)s, %(user_inclusao)s)]
[parameters: {'loja': '99', 'coo': '123456', 'checkout': '999', 'valor': 999.99, 'id_usuario': 954, 'gera_jogada': 1, 'user_inclusao': 'juan.costa'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-02-02 17:17:05,440 - ERROR - service.py:47 - Erro ao gerar jogadas, cliente: 44185567880, erro: 'user_inclusao' is an invalid keyword argument for BakeCompras
2023-02-02 17:35:08,354 - ERROR - service.py:73 - Erro ao buscar informações de compras, CPF: 44185567880 erro: 'BakeCompras' object has no attribute 'user_inclusao'
2023-02-02 17:36:01,571 - ERROR - service.py:73 - Erro ao buscar informações de compras, CPF: 44185567880 erro: 'BakeCompras' object has no attribute 'user_inclusao'
2023-02-02 17:37:47,893 - ERROR - service.py:73 - Erro ao buscar informações de compras, CPF: 44185567880 erro: 'BakeCompras' object has no attribute 'user_inclusao'
2023-02-02 17:39:12,639 - ERROR - service.py:73 - Erro ao buscar informações de compras, CPF: 44185567880 erro: 'BakeCompras' object has no attribute 'user_inclusao'
2023-02-02 17:40:13,409 - ERROR - service.py:73 - Erro ao buscar informações de compras, CPF: 44185567880 erro: 'BakeCompras' object has no attribute 'user_inclusao'
2023-02-02 17:41:33,329 - ERROR - service.py:73 - Erro ao buscar informações de compras, CPF: 44185567880 erro: 'BakeCompras' object has no attribute 'user_inclusao'
2023-02-02 17:57:49,030 - ERROR - service.py:211 - Erro ao buscar informações, voucher: 7966200010200954, erro: name 'Produto' is not defined
2023-02-02 17:58:48,985 - ERROR - service.py:211 - Erro ao buscar informações, voucher: 7966200010200954, erro: name 'Produto' is not defined
2023-02-03 13:56:55,723 - ERROR - service_vouchers.py:56 - Erro ao ativar voucher, voucher: 245941001120095, erro: list index out of range
2023-02-03 14:04:08,752 - ERROR - service_jogadas.py:114 - Erro ao buscar informações, cliente: 44185567880, erro: busca_id_cliente() missing 1 required positional argument: 'valor'
2023-02-03 14:04:11,548 - ERROR - service_jogadas.py:114 - Erro ao buscar informações, cliente: 44185567880, erro: busca_id_cliente() missing 1 required positional argument: 'valor'
2023-02-03 14:05:04,720 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2932200011300954, erro: 'DBconnection' object has no attribute 'query'
2023-02-03 14:05:23,670 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2932200011300954, erro: 'DBconnection' object has no attribute 'query'
2023-02-03 14:07:02,809 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'bool' object has no attribute 'id_produto'
2023-02-03 14:07:18,680 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'bool' object has no attribute 'id_produto'
2023-02-03 14:11:15,328 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'bool' object has no attribute 'id_produto'
2023-02-03 14:11:38,960 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'bool' object has no attribute 'id_produto'
2023-02-03 14:12:22,647 - ERROR - service_vouchers.py:58 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'bool' object is not subscriptable
2023-02-03 14:19:33,474 - ERROR - service_vouchers.py:59 - Erro ao ativar voucher, voucher: 245959001110095, erro: list index out of range
2023-02-03 14:19:51,439 - ERROR - service_vouchers.py:59 - Erro ao ativar voucher, voucher: 245959001110095, erro: list index out of range
2023-02-03 14:19:56,090 - ERROR - service_vouchers.py:59 - Erro ao ativar voucher, voucher: 245959001110095, erro: list index out of range
2023-02-03 14:20:17,035 - ERROR - service_vouchers.py:59 - Erro ao ativar voucher, voucher: 245959001110095, erro: list index out of range
2023-02-03 14:20:48,623 - ERROR - service_vouchers.py:59 - Erro ao ativar voucher, voucher: 245959001110095, erro: list index out of range
2023-02-03 14:22:20,244 - ERROR - service_vouchers.py:61 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'list' object has no attribute 'id_produto'
2023-02-03 14:29:22,395 - ERROR - service_vouchers.py:69 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'list' object has no attribute 'ativo'
2023-02-03 14:29:39,871 - ERROR - service_vouchers.py:69 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'list' object has no attribute 'ativo'
2023-02-03 14:30:35,232 - ERROR - service_vouchers.py:69 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'list' object has no attribute 'id_produto'
2023-02-03 14:30:56,155 - ERROR - service_vouchers.py:69 - Erro ao ativar voucher, voucher: 2459590011100954, erro: 'BakeProdutos' object has no attribute 'codigo_acesso'
2023-02-03 15:05:48,416 - ERROR - service_vouchers.py:71 - Erro ao ativar voucher, voucher: 2932200011300954, erro: get() missing 1 required positional argument: 'url'
2023-02-03 15:06:21,571 - ERROR - service_vouchers.py:71 - Erro ao ativar voucher, voucher: 2459410011200954, erro: get() missing 1 required positional argument: 'url'
2023-02-03 16:55:09,398 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: 'dict' object has no attribute 'valorC5'
2023-02-03 16:55:46,397 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: 'valorC5'
2023-02-03 16:56:16,375 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: list indices must be integers or slices, not str
2023-02-03 16:56:40,204 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: 0
2023-02-03 16:57:03,618 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: 0
2023-02-03 16:58:24,033 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: list indices must be integers or slices, not str
2023-02-03 16:58:44,996 - ERROR - service_vouchers.py:74 - Erro ao ativar voucher, voucher: 2459410011200954, erro: 'list' object has no attribute 'valorC5'
2023-02-06 11:56:36,386 - ERROR - service_vouchers.py:41 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 11:57:42,995 - ERROR - service_vouchers.py:41 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 11:58:33,523 - ERROR - service_vouchers.py:42 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 11:58:59,973 - ERROR - service_vouchers.py:42 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 11:59:36,540 - ERROR - service_vouchers.py:42 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 12:00:41,997 - ERROR - service_vouchers.py:42 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 12:01:19,629 - ERROR - service_vouchers.py:42 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 12:01:46,543 - ERROR - service_vouchers.py:42 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_produto'
2023-02-06 12:02:47,040 - ERROR - service_vouchers.py:45 - Erro ao buscar informações, voucher: 2932200011300954, erro: 'list' object has no attribute 'id_usuario'
2023-02-06 12:25:44,762 - ERROR - service_vouchers.py:102 - Erro ao ativar voucher, voucher: 8646200011400954, erro: 3 validation errors for Voucher
data_inclusao
  str type expected (type=type_error.str)
data_vencimento
  str type expected (type=type_error.str)
data_atualizacao
  str type expected (type=type_error.str)
2023-02-06 14:29:03,490 - ERROR - service_jogadas.py:112 - Erro ao buscar informações, cliente: 44185567880, erro: 'list' object has no attribute 'cod_acesso'
2023-02-06 14:29:13,242 - ERROR - service_jogadas.py:112 - Erro ao buscar informações, cliente: 44185567880, erro: 'list' object has no attribute 'cod_acesso'
2023-02-06 14:33:13,508 - ERROR - service_vouchers.py:101 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 14:34:05,877 - ERROR - service_vouchers.py:101 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 14:35:03,217 - ERROR - service_vouchers.py:101 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 15:13:57,084 - ERROR - service_vouchers.py:101 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 15:14:37,112 - ERROR - service_vouchers.py:101 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 15:17:04,974 - ERROR - service_vouchers.py:102 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 15:17:24,955 - ERROR - service_vouchers.py:102 - Erro ao ativar voucher, voucher: 9463400011500954, erro: 'itens'
2023-02-06 19:07:46,282 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: (pymysql.err.OperationalError) (1305, 'FUNCTION meunagumo.trunc does not exist')
[SQL: SELECT trunc(CURRENT_TIMESTAMP, %(trunc_2)s) AS trunc_1]
[parameters: {'trunc_2': 'month'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-02-06 19:08:56,619 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: (pymysql.err.OperationalError) (1305, 'FUNCTION meunagumo.trunc does not exist')
[SQL: SELECT trunc(bake_vouchers.data_atualizacao, %(trunc_2)s) AS trunc_1 
FROM bake_vouchers]
[parameters: {'trunc_2': 'month'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-02-06 19:11:05,206 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS truncate_1 \nFROM bake_vouchers' at line 1")
[SQL: SELECT truncate(bake_vouchers.data_inclusao) AS truncate_1 
FROM bake_vouchers]
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-02-06 19:14:06,931 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: Cast.__init__() missing 1 required positional argument: 'type_'
2023-02-06 19:24:44,985 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: 'Session' object has no attribute 'engine'
2023-02-06 19:25:39,593 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: 'Session' object has no attribute 'get_engine'
2023-02-06 19:25:41,966 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: 'Session' object has no attribute 'get_engine'
2023-02-06 19:52:00,826 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: 'Session' object has no attribute 'get_engine'
2023-02-06 19:53:09,644 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: 'function' object has no attribute 'execute'
2023-02-06 19:54:00,584 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: 'Session' object has no attribute 'get_engine'
2023-02-06 20:19:45,475 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: unconverted data remains: 23
2023-02-06 20:20:28,299 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data '2023-02-06' does not match format '%d-%m-%y'
2023-02-06 20:20:52,490 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data '2023-02-06' does not match format '%y-%m-%d'
2023-02-06 20:25:07,095 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data '2023-02-06' does not match format '%d-%m-%y'
2023-02-06 20:25:21,904 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data '2023-02-06' does not match format '%y-%m-%d'
2023-02-06 20:25:47,192 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data '2023-02-06' does not match format '%y-%m-%d'
2023-02-06 20:48:41,446 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data '2023-02-06' does not match format '%y-%m-%d'
2023-02-07 13:53:58,805 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data 'undefined' does not match format '%Y-%m-%d'
2023-02-07 13:55:51,454 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: time data 'undefined' does not match format '%Y-%m-%d'
2023-02-07 16:23:05,129 - ERROR - service_vouchers.py:26 - Erro ao buscar informações, erro: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'rds.meunagumo.com.br' (timed out)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-02-15 15:48:45,775 - ERROR - service_jogadas.py:170 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-02-16 12:12:40,394 - ERROR - service_vouchers.py:38 - Erro ao buscar informações, erro: 1 validation error for VoucherResponse
data_inclusao
  str type expected (type=type_error.str)
2023-02-17 16:02:24,686 - ERROR - service_vouchers.py:39 - Erro ao buscar informações, erro: 1 validation error for VoucherResponse
descricao_produto
  field required (type=value_error.missing)
2023-02-17 16:04:25,002 - ERROR - service_vouchers.py:39 - Erro ao buscar informações, erro: 1 validation error for VoucherResponse
descricao_produto
  field required (type=value_error.missing)
2023-03-21 14:44:37,661 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.ProgrammingError) (1146, "Table 'campanhas_nagumo.usuario' doesn't exist")
[SQL: SELECT usuario.id_usuario AS usuario_id_usuario 
FROM usuario 
WHERE usuario.username = %(username_1)s]
[parameters: {'username_1': '44185567880'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-03-21 16:19:34,424 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: Textual column expression 'select id_usuario from me...' should be explicitly declared with text('select id_usuario from me...'), or use literal_column('select id_usuario from me...') for more specificity
2023-03-21 16:21:18,076 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: name 'text' is not defined
2023-03-21 16:21:39,776 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select id_usuario from meunagumo.usuario u where u.username = '44185567880'' at line 1")
[SQL: SELECT select id_usuario from meunagumo.usuario u where u.username = '44185567880']
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-03-21 16:23:17,950 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select u.id_usuario from meunagumo.usuario u where u.username = '44185567880'' at line 1")
[SQL: SELECT select u.id_usuario from meunagumo.usuario u where u.username = '44185567880']
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-03-21 16:23:53,993 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.ProgrammingError) (1146, "Table 'campanhas_nagumo.bake_jogadas' doesn't exist")
[SQL: SELECT bake_jogadas.id_jogada AS bake_jogadas_id_jogada, bake_jogadas.id_compra AS bake_jogadas_id_compra, bake_jogadas.id_usuario AS bake_jogadas_id_usuario, bake_jogadas.data_inclusao AS bake_jogadas_data_inclusao, bake_jogadas.data_utilizacao AS bake_jogadas_data_utilizacao, bake_jogadas.utilizado AS bake_jogadas_utilizado 
FROM bake_jogadas 
WHERE bake_jogadas.id_usuario = %(id_usuario_1)s AND bake_jogadas.utilizado = false]
[parameters: {'id_usuario_1': 954}]
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-03-21 16:24:28,864 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: 'Session' object has no attribute 'select'
2023-03-21 16:25:11,445 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'u.id_usuario from meunagumo.usuario u where u.username = '44185567880'' at line 1")
[SQL: u.id_usuario from meunagumo.usuario u where u.username = '44185567880']
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-03-21 16:25:35,376 - ERROR - service_jogadas.py:113 - Erro ao buscar informações, cliente: 44185567880, erro: (pymysql.err.ProgrammingError) (1146, "Table 'campanhas_nagumo.bake_jogadas' doesn't exist")
[SQL: SELECT bake_jogadas.id_jogada AS bake_jogadas_id_jogada, bake_jogadas.id_compra AS bake_jogadas_id_compra, bake_jogadas.id_usuario AS bake_jogadas_id_usuario, bake_jogadas.data_inclusao AS bake_jogadas_data_inclusao, bake_jogadas.data_utilizacao AS bake_jogadas_data_utilizacao, bake_jogadas.utilizado AS bake_jogadas_utilizado 
FROM bake_jogadas 
WHERE bake_jogadas.id_usuario = %(id_usuario_1)s AND bake_jogadas.utilizado = false]
[parameters: {'id_usuario_1': 954}]
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-03-21 16:48:21,907 - ERROR - service_jogadas.py:58 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 16:49:50,874 - ERROR - service_jogadas.py:59 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 16:50:21,715 - ERROR - service_jogadas.py:60 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 16:51:02,424 - ERROR - service_jogadas.py:60 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:27:41,444 - ERROR - service_jogadas.py:60 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:30:27,409 - ERROR - service_jogadas.py:61 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:32:21,839 - ERROR - service_jogadas.py:61 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:33:34,643 - ERROR - service_jogadas.py:61 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:41:47,567 - ERROR - service_jogadas.py:61 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:44:29,799 - ERROR - service_jogadas.py:61 - Erro ao gerar jogadas, cliente: 44185567880, erro: insere_compra() got an unexpected keyword argument 'compra'
2023-03-21 17:52:53,678 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 17:53:19,248 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 17:54:58,171 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 17:55:22,061 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 17:56:39,888 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 17:58:35,605 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 18:00:09,677 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 18:00:33,524 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 18:00:52,349 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 18:02:41,919 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-21 18:03:40,739 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: 'BakeJogadas' object is not iterable
2023-03-21 18:04:06,529 - ERROR - service_jogadas.py:172 - Erro ao buscar informações, cliente: 44185567880, erro: 'BakeJogadas' object is not iterable
2023-03-21 18:04:31,718 - ERROR - service_jogadas.py:172 - Erro ao buscar informações, cliente: 44185567880, erro: 'BakeJogadas' object is not iterable
2023-03-22 08:08:55,592 - ERROR - service_jogadas.py:173 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:11:34,705 - ERROR - service_jogadas.py:173 - Erro ao buscar informações, cliente: 44185567880, erro: 'NoneType' object has no attribute 'utilizado'
2023-03-22 08:12:40,190 - ERROR - service_jogadas.py:173 - Erro ao buscar informações, cliente: 44185567880, erro: 'NoneType' object has no attribute 'utilizado'
2023-03-22 08:13:14,858 - ERROR - service_jogadas.py:173 - Erro ao buscar informações, cliente: 44185567880, erro: 'NoneType' object has no attribute 'utilizado'
2023-03-22 08:28:18,868 - ERROR - service_jogadas.py:172 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:37:37,595 - ERROR - service_jogadas.py:172 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:42:19,654 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:43:29,899 - ERROR - service_jogadas.py:170 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:44:06,648 - ERROR - service_jogadas.py:170 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:45:31,583 - ERROR - service_jogadas.py:170 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:46:19,704 - ERROR - service_jogadas.py:171 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 08:48:06,295 - ERROR - service_jogadas.py:172 - Erro ao buscar informações, cliente: 44185567880, erro: list index out of range
2023-03-22 11:09:49,125 - ERROR - service_jogadas.py:191 - Erro ao aceitar os termos. Erro: Session.execute() missing 1 required positional argument: 'statement'
2023-03-22 11:14:10,373 - ERROR - service_jogadas.py:191 - Erro ao aceitar os termos. Erro: This result object does not return rows. It has been closed automatically.
2023-03-22 11:23:27,981 - ERROR - service_jogadas.py:194 - Erro ao aceitar os termos. Erro: 
2023-03-22 11:24:38,501 - ERROR - service_jogadas.py:194 - Erro ao aceitar os termos. Erro: 
2023-03-22 11:25:10,541 - ERROR - service_jogadas.py:195 - Erro ao aceitar os termos. Erro: 
2023-03-22 11:25:38,691 - ERROR - service_jogadas.py:195 - Erro ao aceitar os termos. Erro: 
2023-03-22 12:04:20,928 - ERROR - service_jogadas.py:119 - Erro ao buscar informações, cliente: 44185567880, erro: consulta_aceite() got an unexpected keyword argument 'id_user'
2023-03-22 12:05:54,273 - ERROR - service_jogadas.py:119 - Erro ao buscar informações, cliente: 44185567880, erro: object of type 'NoneType' has no len()
2023-03-22 12:06:44,713 - ERROR - service_jogadas.py:119 - Erro ao buscar informações, cliente: 44185567880, erro: 'NoneType' object is not subscriptable
2023-03-22 13:27:52,782 - ERROR - service_jogadas.py:119 - Erro ao buscar informações, cliente: 44378162857, erro: 'NoneType' object is not subscriptable
2023-03-22 13:33:39,335 - ERROR - service_jogadas.py:119 - Erro ao buscar informações, cliente: 44378162857, erro: 'NoneType' object is not subscriptable
